name: "Issue Defaults"
description: Auto-assign default issue properties.
title: "<Enter issue title>"
projects: ["aliceroherty/1"]
assignees:
  - aliceroherty
body:
  - type: markdown
    attributes:
      value: |
        Provide a description.
