/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export function KeyboardModel(props) {
	const [position, setPosition] = useState([2.25, 0.5, 0]);
	const { nodes, materials } = useGLTF('/assets/keyboard.glb');

	// Tailwind breakpoints
	const sizes = {
		sm: '640px',
		md: '768px',
		lg: '1024px',
		xl: '1280px',
		'2xl': '1536px',
	};

	const myMesh = useRef();

	useEffect(() => {
		positionMesh();
		window.onresize = positionMesh;
	});

	useFrame(() => {
		myMesh.current.rotation.y += 0.005;
	});

	const positionMesh = () => {
		if (window.matchMedia(`screen and (min-width: ${sizes.xl})`).matches) {
			setPosition([2.25, 0.5, 0]);
		} else if (
			window.matchMedia(`screen and (min-width: ${sizes.lg})`).matches
		) {
			setPosition([0, -0.6, 0]);
		} else {
			setPosition([0, -1, -3]);
		}
	};

	return (
		<group {...props} dispose={null}>
			<group
				rotation={[0, 0, 0]}
				scale={0.7}
				position={position}
				ref={myMesh}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube001.geometry}
					material={materials['Material.060']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube001_1.geometry}
					material={materials['Material.064']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube001_2.geometry}
					material={materials['Material.069']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube001_3.geometry}
					material={materials['Material.001']}
					position={[-3.49, 1, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text100.geometry}
						material={materials['Material.061']}
						position={[0, 3.85, -0.52]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube002.geometry}
					material={materials['Material.024']}
					position={[-2.99, 1, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text130.geometry}
						material={materials['Material.061']}
						position={[0.1, 3.89, -0.39]}
						scale={[0.28, 2.93, 0.35]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text132.geometry}
						material={materials['Material.061']}
						position={[-0.12, 3.89, -0.41]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube003.geometry}
					material={materials['Material.023']}
					position={[-2.49, 1, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text128.geometry}
						material={materials['Material.061']}
						position={[0.15, 3.89, -0.36]}
						scale={[0.25, 2.93, 0.31]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text129.geometry}
						material={materials['Material.061']}
						position={[-0.2, 3.89, -0.45]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube004.geometry}
					material={materials['Material.022']}
					position={[-1.99, 1, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text126.geometry}
						material={materials['Material.061']}
						position={[0.14, 3.89, -0.38]}
						scale={[0.28, 2.93, 0.35]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text127.geometry}
						material={materials['Material.061']}
						position={[-0.22, 3.89, -0.41]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube005.geometry}
					material={materials['Material.021']}
					position={[-1.48, 1, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text124.geometry}
						material={materials['Material.061']}
						position={[0.16, 3.89, -0.4]}
						scale={[0.28, 2.93, 0.35]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text125.geometry}
						material={materials['Material.061']}
						position={[-0.18, 3.89, -0.4]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube006.geometry}
					material={materials['Material.025']}
					position={[-0.98, 1, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text122.geometry}
						material={materials['Material.061']}
						position={[0.26, 3.89, -0.37]}
						scale={[0.28, 2.93, 0.35]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text123.geometry}
						material={materials['Material.061']}
						position={[-0.19, 3.89, -0.34]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube007.geometry}
					material={materials['Material.032']}
					position={[-0.48, 1, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text118.geometry}
						material={materials['Material.061']}
						position={[0.17, 3.89, -0.45]}
						scale={[0.28, 2.93, 0.35]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text119.geometry}
						material={materials['Material.061']}
						position={[-0.17, 3.89, -0.38]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube008.geometry}
					material={materials['Material.033']}
					position={[0.02, 1, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text116.geometry}
						material={materials['Material.061']}
						position={[0.17, 3.89, -0.4]}
						scale={[0.28, 2.93, 0.35]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text117.geometry}
						material={materials['Material.061']}
						position={[-0.21, 3.89, -0.44]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube009.geometry}
					material={materials['Material.040']}
					position={[0.52, 1, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text114.geometry}
						material={materials['Material.061']}
						position={[0.18, 3.89, -0.48]}
						scale={[0.28, 2.93, 0.35]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text115.geometry}
						material={materials['Material.061']}
						position={[-0.15, 3.89, -0.41]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube010.geometry}
					material={materials['Material.041']}
					position={[1.02, 1, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text112.geometry}
						material={materials['Material.061']}
						position={[0.14, 3.89, -0.36]}
						scale={[0.28, 2.93, 0.35]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text113.geometry}
						material={materials['Material.061']}
						position={[-0.18, 3.89, -0.44]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube011.geometry}
					material={materials['Material.050']}
					position={[1.52, 1, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text110.geometry}
						material={materials['Material.061']}
						position={[0.16, 3.89, -0.36]}
						scale={[0.28, 2.93, 0.35]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text111.geometry}
						material={materials['Material.061']}
						position={[-0.16, 3.89, -0.41]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube012.geometry}
					material={materials['Material.051']}
					position={[2.03, 1, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text108.geometry}
						material={materials['Material.061']}
						position={[0.07, 3.89, -0.22]}
						scale={[0.4, 4.27, 0.51]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text109.geometry}
						material={materials['Material.061']}
						position={[-0.16, 3.89, -0.36]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube013.geometry}
					material={materials['Material.002']}
					position={[-3.36, 0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text095.geometry}
						material={materials['Material.061']}
						position={[-0.42, 3.85, -0.38]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube014.geometry}
					material={materials['Material.059']}
					position={[2.53, 1, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text107.geometry}
						material={materials['Material.061']}
						position={[-0.18, 3.89, -0.41]}
						scale={[0.4, 4.27, 0.51]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text142.geometry}
						material={materials['Material.061']}
						position={[0.11, 3.89, -0.41]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube015.geometry}
					material={materials['Material.012']}
					position={[-2.72, 0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text092.geometry}
						material={materials['Material.061']}
						position={[-0.04, 3.89, -0.31]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube016.geometry}
					material={materials['Material.013']}
					position={[-2.22, 0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text091.geometry}
						material={materials['Material.061']}
						position={[0, 3.89, -0.36]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube017.geometry}
					material={materials['Material.014']}
					position={[-1.72, 0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text090.geometry}
						material={materials['Material.061']}
						position={[0.04, 3.89, -0.34]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube018.geometry}
					material={materials['Material.020']}
					position={[-1.22, 0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text089.geometry}
						material={materials['Material.061']}
						position={[-0.02, 3.89, -0.35]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube019.geometry}
					material={materials['Material.026']}
					position={[-0.72, 0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text088.geometry}
						material={materials['Material.061']}
						position={[0.01, 3.89, -0.4]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube020.geometry}
					material={materials['Material.031']}
					position={[-0.21, 0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text087.geometry}
						material={materials['Material.061']}
						position={[-0.04, 3.89, -0.38]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube021.geometry}
					material={materials['Material.034']}
					position={[0.29, 0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text086.geometry}
						material={materials['Material.061']}
						position={[0, 3.89, -0.27]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube022.geometry}
					material={materials['Material.039']}
					position={[0.79, 0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text085.geometry}
						material={materials['Material.061']}
						position={[-0.06, 3.89, -0.34]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube023.geometry}
					material={materials['Material.042']}
					position={[1.29, 0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text084.geometry}
						material={materials['Material.061']}
						position={[-0.04, 3.89, -0.34]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube024.geometry}
					material={materials['Material.049']}
					position={[1.79, 0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text083.geometry}
						material={materials['Material.061']}
						position={[0.03, 3.89, -0.4]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube025.geometry}
					material={materials['Material.052']}
					position={[2.29, 0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text081.geometry}
						material={materials['Material.061']}
						position={[0.13, 3.89, -0.31]}
						scale={[0.4, 4.27, 0.51]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text082.geometry}
						material={materials['Material.061']}
						position={[-0.05, 3.89, -0.3]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube026.geometry}
					material={materials['Material.062']}
					position={[2.8, 0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text079.geometry}
						material={materials['Material.061']}
						position={[0.19, 3.89, -0.31]}
						scale={[0.4, 4.27, 0.51]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text080.geometry}
						material={materials['Material.061']}
						position={[-0.03, 3.89, -0.3]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube027.geometry}
					material={materials['Material.011']}
					position={[-2.6, 0, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text067.geometry}
						material={materials['Material.061']}
						position={[0, 3.85, -0.31]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube028.geometry}
					material={materials['Material.010']}
					position={[-2.1, 0, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text066.geometry}
						material={materials['Material.061']}
						position={[-0.04, 3.85, -0.35]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube029.geometry}
					material={materials['Material.015']}
					position={[-1.6, 0, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text065.geometry}
						material={materials['Material.061']}
						position={[0.03, 3.85, -0.35]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube030.geometry}
					material={materials['Material.019']}
					position={[-1.1, 0, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text064.geometry}
						material={materials['Material.061']}
						position={[0.02, 3.85, -0.37]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube031.geometry}
					material={materials['Material.027']}
					position={[-0.6, 0, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text063.geometry}
						material={materials['Material.061']}
						position={[-0.03, 3.85, -0.34]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube032.geometry}
					material={materials['Material.030']}
					position={[-0.09, 0, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text062.geometry}
						material={materials['Material.061']}
						position={[0, 3.85, -0.35]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube033.geometry}
					material={materials['Material.035']}
					position={[0.41, 0, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text061.geometry}
						material={materials['Material.061']}
						position={[-0.05, 3.85, -0.15]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube034.geometry}
					material={materials['Material.038']}
					position={[0.91, 0, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text060.geometry}
						material={materials['Material.061']}
						position={[-0.05, 3.85, -0.35]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube035.geometry}
					material={materials['Material.043']}
					position={[1.41, 0, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text059.geometry}
						material={materials['Material.061']}
						position={[-0.08, 3.85, -0.31]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube036.geometry}
					material={materials['Material.048']}
					position={[1.91, 0, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text055.geometry}
						material={materials['Material.061']}
						position={[0.14, 3.85, -0.37]}
						scale={[0.4, 4.27, 0.51]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text056.geometry}
						material={materials['Material.061']}
						position={[0.14, 3.85, -0.22]}
						scale={[0.4, 4.27, 0.51]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text057.geometry}
						material={materials['Material.061']}
						position={[-0.12, 3.85, -0.37]}
						scale={[0.4, 4.27, 0.51]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text058.geometry}
						material={materials['Material.061']}
						position={[-0.12, 3.85, -0.21]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube037.geometry}
					material={materials['Material.063']}
					position={[2.41, 0, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text052.geometry}
						material={materials['Material.061']}
						position={[0.17, 3.85, -0.45]}
						scale={[0.4, 4.27, 0.51]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text053.geometry}
						material={materials['Material.061']}
						position={[0.12, 3.85, -0.45]}
						scale={[0.4, 4.27, 0.51]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text054.geometry}
						material={materials['Material.061']}
						position={[-0.13, 3.85, -0.45]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube038.geometry}
					material={materials['Material.009']}
					position={[-2.34, -0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text040.geometry}
						material={materials['Material.061']}
						position={[0, 3.82, -0.33]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube039.geometry}
					material={materials['Material.008']}
					position={[-1.84, -0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text039.geometry}
						material={materials['Material.061']}
						position={[-0.01, 3.82, -0.33]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube040.geometry}
					material={materials['Material.016']}
					position={[-1.34, -0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text038.geometry}
						material={materials['Material.061']}
						position={[-0.02, 3.82, -0.33]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube041.geometry}
					material={materials['Material.018']}
					position={[-0.83, -0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text037.geometry}
						material={materials['Material.061']}
						position={[-0.02, 3.82, -0.36]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube042.geometry}
					material={materials['Material.028']}
					position={[-0.33, -0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text036.geometry}
						material={materials['Material.061']}
						position={[0.02, 3.82, -0.33]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube043.geometry}
					material={materials['Material.029']}
					position={[0.17, -0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text035.geometry}
						material={materials['Material.061']}
						position={[0, 3.82, -0.33]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube044.geometry}
					material={materials['Material.036']}
					position={[0.67, -0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text034.geometry}
						material={materials['Material.061']}
						position={[0.02, 3.82, -0.35]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube045.geometry}
					material={materials['Material.037']}
					position={[1.17, -0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text032.geometry}
						material={materials['Material.061']}
						position={[0.18, 3.82, -0.34]}
						scale={[0.4, 4.27, 0.51]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text033.geometry}
						material={materials['Material.061']}
						position={[-0.16, 3.82, -0.19]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube046.geometry}
					material={materials['Material.044']}
					position={[1.67, -0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text030.geometry}
						material={materials['Material.061']}
						position={[0.17, 3.82, -0.34]}
						scale={[0.4, 4.27, 0.51]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text031.geometry}
						material={materials['Material.061']}
						position={[-0.13, 3.82, -0.21]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube047.geometry}
					material={materials['Material.047']}
					position={[2.17, -0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text028.geometry}
						material={materials['Material.061']}
						position={[0.18, 3.82, -0.31]}
						scale={[0.4, 4.27, 0.51]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text029.geometry}
						material={materials['Material.061']}
						position={[-0.1, 3.82, -0.33]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube048.geometry}
					material={materials['Material.005']}
					position={[-3.42, -1.01, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text020.geometry}
						material={materials['Material.061']}
						position={[-0.29, 3.84, -0.18]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube049.geometry}
					material={materials['Material.006']}
					position={[-2.79, -1.01, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Plane001.geometry}
						material={materials['Material.061']}
						position={[-0.01, 3.86, -0.22]}
						scale={[0.3, 3.32, 0.4]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube050.geometry}
					material={materials['Material.007']}
					position={[-2.17, -1.01, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text016.geometry}
						material={materials['Material.061']}
						position={[-0.02, 3.84, -0.11]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube051.geometry}
					material={materials['Material.045']}
					position={[1.57, -1.01, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text007.geometry}
						material={materials['Material.061']}
						position={[0.12, 3.84, -0.11]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube052.geometry}
					material={materials['Material.046']}
					position={[2.2, -1.01, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Plane.geometry}
						material={materials['Material.061']}
						position={[0, 3.88, -0.23]}
						scale={[0.29, 3.1, 0.43]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube053.geometry}
					material={materials['Material.054']}
					position={[2.82, -1.01, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text004.geometry}
						material={materials['Material.061']}
						position={[0.02, 3.84, -0.21]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube054.geometry}
					material={materials['Material.055']}
					position={[3.45, -1.01, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text001.geometry}
						material={materials['Material.061']}
						position={[-0.02, 3.84, -0.18]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube055.geometry}
					material={materials['Material.004']}
					position={[-3.18, -0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text043.geometry}
						material={materials['Material.061']}
						position={[-1.06, 3.85, -0.26]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube056.geometry}
					material={materials['Material.053']}
					position={[3.09, -0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text002.geometry}
						material={materials['Material.061']}
						position={[-0.05, 3.85, -0.26]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube057.geometry}
					material={materials['Material.056']}
					position={[3.21, 0, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text049.geometry}
						material={materials['Material.061']}
						position={[0.02, 3.85, -0.29]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube058.geometry}
					material={materials['Material.057']}
					position={[3.4, 0.5, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text077.geometry}
						material={materials['Material.061']}
						position={[0.2, 3.85, -0.39]}
						scale={[0.4, 4.27, 0.51]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text078.geometry}
						material={materials['Material.061']}
						position={[-0.08, 3.85, -0.44]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube059.geometry}
					material={materials['Material.058']}
					position={[3.26, 0.99, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text003.geometry}
						material={materials['Material.061']}
						position={[-0.02, 3.85, -0.48]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube060.geometry}
					material={materials['Material.003']}
					position={[-3.31, 0, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text069.geometry}
						material={materials['Material.061']}
						position={[-0.38, 3.85, -0.3]}
						scale={[0.4, 4.27, 0.51]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube061.geometry}
					material={materials['Material.017']}
					position={[-0.29, -1.02, 0.28]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Text009.geometry}
						material={materials['Material.061']}
						position={[-0.08, 3.92, -0.47]}
						scale={[0.4, 4.27, 0.9]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube062.geometry}
					material={materials['Material.055']}
					position={[3.45, -1.01, 0.17]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube063.geometry}
					material={materials['Material.002']}
					position={[-3.36, 0.5, 0.16]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				/>
				<group
					position={[-0.06, 0.12, 0.17]}
					rotation={[1.62, 0, 0]}
					scale={[0.31, 0.03, 0.24]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube117.geometry}
						material={materials['Material.067']}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube117_1.geometry}
						material={materials['Material.068']}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/assets/keyboard.glb');
