/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/assets/keyboard.glb --draco --simplify --transform --root=./public/assets --output=./src/components/Keyboard/Model-new.jsx 
Files: ./public/assets/keyboard.glb [7.21MB] > /home/aliceroherty/git/portfolio/portfolio-client/src/components/Keyboard/keyboard-transformed.glb [415.23KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/../../src/components/Keyboard/keyboard-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.PaletteMaterial001} />
      </group>
    </group>
  )
}

useGLTF.preload('/../../src/components/Keyboard/keyboard-transformed.glb')
